package com.herinoid.rsi.gui;

import com.herinoid.rsi.dao.GambarRadiologiDao;
import com.herinoid.rsi.model.GambarRadiologi;
import com.herinoid.rsi.table.DefaultTableCellRender;
import com.herinoid.rsi.table.TabelGambarRadiologi;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;

public class DlgFoundImageRadiologi extends javax.swing.JDialog {

//    private List<GambarRadiologi> gambarRadiologis;
    private TabelGambarRadiologi modelRadiologi;

    /**
     * Creates new form DlgProgramStudi
     *
     * @param parent
     * @param modal
     */
    public DlgFoundImageRadiologi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        gambarRadiologis = new LinkedList<>();
        modelRadiologi = new TabelGambarRadiologi();
    }

    public void setData(String norawat, String tanggal, String pasien, String petugas,List<GambarRadiologi> gambarRadiologis) {
        lblNorawat.setText(norawat);
        lblTanggal.setText(tanggal);
        lblPasien.setText(pasien);
        lblPetugas.setText(petugas);
//        this.gambarRadiologis = gambarRadiologis;
        modelRadiologi.removeAllElements();
        modelRadiologi.add(new HashSet<>(gambarRadiologis));
        tabelGambar.setModel(modelRadiologi);
        for (int i = 0; i < tabelGambar.getColumnCount(); i++) {
            tabelGambar.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        scrollPane1 = new widget.ScrollPane();
        tabelGambar = new widget.Table();
        panelisi3 = new widget.panelisi();
        lblPetugas = new widget.Label();
        label11 = new widget.Label();
        label16 = new widget.Label();
        label13 = new widget.Label();
        label17 = new widget.Label();
        lblNorawat = new widget.Label();
        lblTanggal = new widget.Label();
        lblPasien = new widget.Label();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Data Gambar Hasil CT Scan Pasien Radiologi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tabelGambar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelGambar.setName("tabelGambar"); // NOI18N
        tabelGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGambarMouseClicked(evt);
            }
        });
        tabelGambar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelGambarKeyPressed(evt);
            }
        });
        scrollPane1.setViewportView(tabelGambar);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 73));
        panelisi3.setLayout(null);

        lblPetugas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPetugas.setText("No.Rawat :");
        lblPetugas.setName("lblPetugas"); // NOI18N
        lblPetugas.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblPetugas);
        lblPetugas.setBounds(460, 40, 340, 23);

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi3.add(label11);
        label11.setBounds(0, 40, 75, 23);

        label16.setText("Pasien :");
        label16.setName("label16"); // NOI18N
        label16.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label16);
        label16.setBounds(385, 10, 60, 23);

        label13.setText("Petugas :");
        label13.setName("label13"); // NOI18N
        label13.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi3.add(label13);
        label13.setBounds(385, 40, 60, 23);

        label17.setText("No.Rawat :");
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label17);
        label17.setBounds(0, 10, 75, 23);

        lblNorawat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNorawat.setText("No.Rawat :");
        lblNorawat.setName("lblNorawat"); // NOI18N
        lblNorawat.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblNorawat);
        lblNorawat.setBounds(80, 10, 200, 23);

        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTanggal.setText("No.Rawat :");
        lblTanggal.setName("lblTanggal"); // NOI18N
        lblTanggal.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblTanggal);
        lblTanggal.setBounds(80, 40, 200, 23);

        lblPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasien.setText("No.Rawat :");
        lblPasien.setName("lblPasien"); // NOI18N
        lblPasien.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblPasien);
        lblPasien.setBounds(460, 10, 360, 23);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 9));

        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed

    }//GEN-LAST:event_BtnKeluarKeyPressed

private void tabelGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGambarMouseClicked
    int row = tabelGambar.getSelectedRow();
    String filename = tabelGambar.getValueAt(row, 3).toString();
    DlgGambarRadiologi gambar = new DlgGambarRadiologi(null, true);
    gambar.setGambar(filename);
    gambar.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
    gambar.setLocationRelativeTo(internalFrame1);
    gambar.setVisible(true);
}//GEN-LAST:event_tabelGambarMouseClicked

private void tabelGambarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelGambarKeyPressed

}//GEN-LAST:event_tabelGambarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgFoundImageRadiologi dialog = new DlgFoundImageRadiologi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label13;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label9;
    private widget.Label lblNorawat;
    private widget.Label lblPasien;
    private widget.Label lblPetugas;
    private widget.Label lblTanggal;
    private widget.panelisi panelisi1;
    private widget.panelisi panelisi3;
    private widget.ScrollPane scrollPane1;
    private widget.Table tabelGambar;
    // End of variables declaration//GEN-END:variables

}
