/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package com.herinoid.rsi.gui;

import com.herinoid.rsi.dao.DokterPoliDao;
import inventory.*;
import fungsi.koneksiDB;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.herinoid.rsi.model.DetailPemberianObat;
import com.herinoid.rsi.model.DokterPoli;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import com.herinoid.rsi.table.DefaultTableCellRender;
import com.herinoid.rsi.table.TabelObatPilihan;
import com.herinoid.rsi.table.TabelRuangPoli;
import com.herinoid.rsi.util.Utils;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author dosen
 */
public final class RuangDokter extends javax.swing.JDialog {

    private Connection koneksi = koneksiDB.condb();
    private List<DokterPoli> dokterPolis;
    private TabelRuangPoli modelPoli;

    /**
     * Creates new form DlgPenyakit
     *
     * @param parent
     * @param modal
     */
    public RuangDokter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10, 2);
        setSize(656, 250);
        FormInput.setPreferredSize(new Dimension(864, 108));
        dokterPolis = new LinkedList<>();
        modelPoli = new TabelRuangPoli();
        BtnPoli.setVisible(false);
        BtnDokter.setVisible(false);
    }

    public void setData() {
        dokterPolis = DokterPoliDao.getAllDokterPoli();
        modelPoli.removeAllElements();
        modelPoli.add(new HashSet<>(dokterPolis));
        tblPoli.setModel(modelPoli);
        for (int i = 0; i < tblPoli.getColumnCount(); i++) {
            tblPoli.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelisi3 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCariData = new widget.Button();
        label13 = new widget.Label();
        BtnSimpan = new widget.Button();
        BtnKeluar = new widget.Button();
        FormInput = new widget.PanelBiasa();
        label12 = new widget.Label();
        cboRuang = new widget.ComboBox();
        label21 = new widget.Label();
        txtKdDokter = new widget.TextBox();
        txtNamaDokter = new widget.TextBox();
        BtnDokter = new widget.Button();
        label22 = new widget.Label();
        txtKdPoli = new widget.TextBox();
        txtNamaPoli = new widget.TextBox();
        BtnPoli = new widget.Button();
        jPanel1 = new javax.swing.JPanel();
        scrollPane1 = new widget.ScrollPane();
        tblPoli = new widget.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pengaturan Display Poliklinik ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi3.setWarnaAtas(new java.awt.Color(204, 204, 255));
        panelisi3.setWarnaBawah(new java.awt.Color(153, 204, 255));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setForeground(new java.awt.Color(0, 0, 0));
        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi3.add(label9);

        TCari.setForeground(new java.awt.Color(0, 0, 0));
        TCari.setToolTipText("Alt+C");
        TCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(285, 23));
        panelisi3.add(TCari);

        BtnCariData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnCariData.setMnemonic('2');
        BtnCariData.setToolTipText("Alt+2");
        BtnCariData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCariData.setName("BtnCariData"); // NOI18N
        BtnCariData.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariDataActionPerformed(evt);
            }
        });
        panelisi3.add(BtnCariData);

        label13.setName("label13"); // NOI18N
        label13.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi3.add(label13);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        panelisi3.add(BtnSimpan);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('4');
        BtnKeluar.setToolTipText("Alt+4");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        FormInput.setBackground(new java.awt.Color(204, 0, 204));
        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(864, 108));
        FormInput.setWarnaAtas(new java.awt.Color(204, 204, 255));
        FormInput.setLayout(null);

        label12.setForeground(new java.awt.Color(51, 51, 51));
        label12.setText("Ruang : ");
        label12.setName("label12"); // NOI18N
        label12.setPreferredSize(new java.awt.Dimension(50, 23));
        FormInput.add(label12);
        label12.setBounds(30, 10, 50, 23);

        cboRuang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ruang A", "Ruang B", "Ruang C", "Ruang D", "Ruang E", "Ruang F", "Ruang G", "Ruang H", "Ruang I", "Ruang J", "Ruang K", "Ruang L", "Ruang M", "Ruang N", "Ruang O", "Ruang P", "Ruang Q", "Ruang R", "Ruang S", "Ruang T", "Ruang U" }));
        cboRuang.setName("cboRuang"); // NOI18N
        cboRuang.setPreferredSize(new java.awt.Dimension(100, 23));
        FormInput.add(cboRuang);
        cboRuang.setBounds(80, 10, 190, 23);

        label21.setForeground(new java.awt.Color(51, 51, 51));
        label21.setText("Dokter :");
        label21.setName("label21"); // NOI18N
        label21.setPreferredSize(new java.awt.Dimension(70, 23));
        FormInput.add(label21);
        label21.setBounds(10, 70, 68, 23);

        txtKdDokter.setEditable(false);
        txtKdDokter.setForeground(new java.awt.Color(0, 0, 0));
        txtKdDokter.setName("txtKdDokter"); // NOI18N
        txtKdDokter.setPreferredSize(new java.awt.Dimension(80, 23));
        FormInput.add(txtKdDokter);
        txtKdDokter.setBounds(80, 70, 110, 23);

        txtNamaDokter.setEditable(false);
        txtNamaDokter.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaDokter.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaDokter.setName("txtNamaDokter"); // NOI18N
        txtNamaDokter.setPreferredSize(new java.awt.Dimension(207, 23));
        FormInput.add(txtNamaDokter);
        txtNamaDokter.setBounds(200, 70, 240, 23);

        BtnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Add patient SH.png"))); // NOI18N
        BtnDokter.setMnemonic('2');
        BtnDokter.setToolTipText("Alt+2");
        BtnDokter.setName("BtnDokter"); // NOI18N
        BtnDokter.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDokterActionPerformed(evt);
            }
        });
        FormInput.add(BtnDokter);
        BtnDokter.setBounds(440, 70, 40, 23);

        label22.setForeground(new java.awt.Color(51, 51, 51));
        label22.setText("Poliklinik :");
        label22.setName("label22"); // NOI18N
        label22.setPreferredSize(new java.awt.Dimension(70, 23));
        FormInput.add(label22);
        label22.setBounds(10, 40, 68, 23);

        txtKdPoli.setEditable(false);
        txtKdPoli.setForeground(new java.awt.Color(0, 0, 0));
        txtKdPoli.setName("txtKdPoli"); // NOI18N
        txtKdPoli.setPreferredSize(new java.awt.Dimension(80, 23));
        FormInput.add(txtKdPoli);
        txtKdPoli.setBounds(80, 40, 110, 23);

        txtNamaPoli.setEditable(false);
        txtNamaPoli.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPoli.setName("txtNamaPoli"); // NOI18N
        txtNamaPoli.setPreferredSize(new java.awt.Dimension(207, 23));
        FormInput.add(txtNamaPoli);
        txtNamaPoli.setBounds(200, 40, 240, 23);

        BtnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Preview.png"))); // NOI18N
        BtnPoli.setMnemonic('2');
        BtnPoli.setToolTipText("Alt+2");
        BtnPoli.setName("BtnPoli"); // NOI18N
        BtnPoli.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPoliActionPerformed(evt);
            }
        });
        FormInput.add(BtnPoli);
        BtnPoli.setBounds(440, 40, 40, 23);

        internalFrame1.add(FormInput, java.awt.BorderLayout.PAGE_START);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tblPoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPoli.setName("tblPoli"); // NOI18N
        tblPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPoliMouseClicked(evt);
            }
        });
        scrollPane1.setViewportView(tblPoli);

        jPanel1.add(scrollPane1);

        internalFrame1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariDataActionPerformed
        dokterPolis = new LinkedList<>();
        dokterPolis = DokterPoliDao.findByDokterName(TCari.getText());
        modelPoli.removeAllElements();
        modelPoli.add(new HashSet<>(dokterPolis));
        tblPoli.setModel(modelPoli);
        for (int i = 0; i < tblPoli.getColumnCount(); i++) {
            tblPoli.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
}//GEN-LAST:event_BtnCariDataActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        modelPoli.removeAllElements();
        dokterPolis = new LinkedList<>();
        dispose();
       
    }//GEN-LAST:event_BtnKeluarActionPerformed

private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
    if(!Utils.isBlank(txtKdDokter.getText()) && !Utils.isBlank(txtKdPoli.getText())){
        if(DokterPoliDao.isExist(txtKdDokter.getText(), txtKdPoli.getText(), cboRuang.getSelectedItem().toString())){
            boolean sukses = DokterPoliDao.update(txtKdDokter.getText(), txtKdPoli.getText(), cboRuang.getSelectedItem().toString());
            if(sukses){
                JOptionPane.showMessageDialog(this, "Data berhasil di update");
                txtKdDokter.setText("");
                txtKdPoli.setText("");
                txtNamaDokter.setText("");
                txtNamaPoli.setText("");
                cboRuang.setSelectedIndex(0);
            }else{
                JOptionPane.showMessageDialog(this, "Gagal mengupdate data");
            }
        }else{
            boolean berhasil = DokterPoliDao.save(txtKdDokter.getText(), txtKdPoli.getText(), cboRuang.getSelectedItem().toString());
            if(berhasil){
                JOptionPane.showMessageDialog(this, "Data berhasil di simpan");
                txtKdDokter.setText("");
                txtKdPoli.setText("");
                txtNamaDokter.setText("");
                txtNamaPoli.setText("");
                cboRuang.setSelectedIndex(0);
            }else{
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
            }
        }
        setData();
    }else{
        JOptionPane.showMessageDialog(this, "Data dokter dan poliklinik tidak boleh kosong!");
    }    
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDokterActionPerformed

    }//GEN-LAST:event_BtnDokterActionPerformed

    private void BtnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPoliActionPerformed

    private void tblPoliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPoliMouseClicked
        // TODO add your handling code here:
        int row = tblPoli.getSelectedRow();
        txtKdPoli.setText(tblPoli.getValueAt(row, 0).toString());
        txtNamaPoli.setText(tblPoli.getValueAt(row, 1).toString());
        txtKdDokter.setText(tblPoli.getValueAt(row, 2).toString());
        txtNamaDokter.setText(tblPoli.getValueAt(row, 3).toString()==null?"-":tblPoli.getValueAt(row, 3).toString());
        cboRuang.setSelectedItem(tblPoli.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblPoliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RuangDokter dialog = new RuangDokter(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCariData;
    private widget.Button BtnDokter;
    private widget.Button BtnKeluar;
    private widget.Button BtnPoli;
    private widget.Button BtnSimpan;
    private widget.PanelBiasa FormInput;
    private widget.TextBox TCari;
    private widget.ComboBox cboRuang;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JPanel jPanel1;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label21;
    private widget.Label label22;
    private widget.Label label9;
    private widget.panelisi panelisi3;
    private widget.ScrollPane scrollPane1;
    private widget.Table tblPoli;
    private widget.TextBox txtKdDokter;
    private widget.TextBox txtKdPoli;
    private widget.TextBox txtNamaDokter;
    private widget.TextBox txtNamaPoli;
    // End of variables declaration//GEN-END:variables

}
