/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

import fungsi.WarnaTable4;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import laporan.DlgBerkasRawat;

/**
 *
 * @author dosen
 */
public final class DlgPilihanCetakDokumen extends javax.swing.JDialog {
    private final DefaultTableModel TabMode;
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private int i=0;
    private String NoRawat="",NoRm="",NoSEP="",NoReg="",NamaPoli="",NamaBayar="",NamaPasien="",
            NamaDokter="",AlamatPasien="",PenanggungJawab="",TanggalDaftar="",JenisPelayanan;

    /**
     * Creates new form DlgPenyakit
     * @param parent
     * @param modal
     */
    public DlgPilihanCetakDokumen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(656,250);

        Object[] row={"P","Pilihan Cetak Dokumen"};
        TabMode=new DefaultTableModel(null,row){
             @Override public boolean isCellEditable(int rowIndex, int colIndex){
                boolean a = false;
                if (colIndex==0) {
                    a=true;
                }
                return a;
             }
             Class[] types = new Class[] {
                java.lang.Boolean.class, java.lang.Object.class
             };
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }
        };
        tbData.setModel(TabMode);
        tbData.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbData.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (i = 0; i < 2; i++) {
            TableColumn column = tbData.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(20);
            }else if(i==1){
                column.setPreferredWidth(400);
            }
        }
        tbData.setDefaultRenderer(Object.class, new WarnaTable4());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        TNoRw = new widget.TextBox();
        Scroll = new widget.ScrollPane();
        tbData = new widget.Table();
        panelisi3 = new widget.panelisi();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        UploadSEP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setMinimumSize(new java.awt.Dimension(600, 610));
        setPreferredSize(new java.awt.Dimension(600, 610));
        setResizable(false);

        internalFrame1.setBackground(new java.awt.Color(51, 51, 255));
        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.MatteBorder(null)), "::[ Copy no.SEP dibawah ini untuk save PDF dan upload ke Vedika ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        internalFrame1.setForeground(new java.awt.Color(0, 204, 204));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        TNoRw.setBackground(new java.awt.Color(245, 250, 240));
        TNoRw.setName("TNoRw"); // NOI18N
        TNoRw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoRwActionPerformed(evt);
            }
        });
        internalFrame1.add(TNoRw, java.awt.BorderLayout.PAGE_START);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbData.setAutoCreateRowSorter(true);
        tbData.setName("tbData"); // NOI18N
        Scroll.setViewportView(tbData);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(44, 54));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        panelisi3.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('U');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+U");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar);

        UploadSEP.setBackground(new java.awt.Color(255, 0, 153));
        UploadSEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UploadSEP.setText("Upload SEP ke Vedika");
        UploadSEP.setName("UploadSEP"); // NOI18N
        UploadSEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadSEPActionPerformed(evt);
            }
        });
        panelisi3.add(UploadSEP);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        for(i=0;i<tbData.getRowCount();i++){ 
            if(tbData.getValueAt(i,0).toString().equals("true")){
                if(tbData.getValueAt(i,1).toString().equals("Bukti Registrasi")){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    param.put("logo",Sequel.cariGambar("select logo from setting"));
                    Valid.MyReportqry("rptBuktiRegister.jasper","report","::[ Bukti Register ]::",
                           "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,pasien.no_tlp,"+
                           "reg_periksa.kd_dokter,dokter.nm_dokter,reg_periksa.no_rkm_medis,pasien.nm_pasien,pasien.jk,pasien.umur as umur,poliklinik.nm_poli,"+
                           "reg_periksa.p_jawab,reg_periksa.almt_pj,reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.stts_daftar,penjab.png_jawab "+
                           "from reg_periksa inner join dokter inner join pasien inner join poliklinik inner join penjab "+
                           "on reg_periksa.kd_dokter=dokter.kd_dokter and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                           "and reg_periksa.kd_pj=penjab.kd_pj and reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.no_rawat='"+NoRawat+"' ",param);
                    this.setCursor(Cursor.getDefaultCursor());
                }else if(tbData.getValueAt(i,1).toString().equals("Label Pasien")){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                    param.put("nama",NamaPasien);
                    param.put("alamat",Sequel.cariIsi("select date_format(tgl_lahir,'%d/%m/%Y') from pasien where no_rkm_medis=?",NoRm));
                    param.put("norm",NoRm);    
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());   
                    Valid.MyReportqry("rptBarcodeRawat.jasper","report","::[ Barcode No.Rawat ]::",
                            "SELECT reg_periksa.no_rawat,pasien.nm_pasien,reg_periksa.no_rkm_medis,pasien.tgl_lahir,pasien.no_ktp FROM reg_periksa INNER JOIN pasien ON reg_periksa.no_rkm_medis=pasien.no_rkm_medis WHERE reg_periksa.no_rawat='"+NoRawat+"'",param); 
                    this.setCursor(Cursor.getDefaultCursor()); 
                }else if(tbData.getValueAt(i,1).toString().equals("Cetak Kartu Pasien")){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();                 
                    param.put("nama",NamaPasien);
                    param.put("alamat",Sequel.cariIsi("select date_format(tgl_lahir,'%d/%m/%Y') from pasien where no_rkm_medis=?",NoRm));
                    param.put("norm",NoRm);    
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());   
                    Valid.MyReportqry("rptBarcodeRawat2.jasper","report","::[ Barcode No.Rawat ]::",
                            "select reg_periksa.no_rawat from reg_periksa where no_rawat='"+NoRawat+"'",param);
                    this.setCursor(Cursor.getDefaultCursor());
                }else if(tbData.getValueAt(i,1).toString().equals("Lembar SEP Model 1")){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
                    Map<String, Object> param = new HashMap<>();
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("logo",Sequel.cariGambar("select bpjs from gambar")); 
                    param.put("prb",Sequel.cariIsi("select prb from bpjs_prb where no_sep=?",NoSEP));            
                    if(JenisPelayanan.equals("ranap")){
                        Valid.MyReportqry("rptBridgingSEP.jasper","report","::[ Cetak SEP ]::","select bridging_sep.no_sep, bridging_sep.no_rawat,bridging_sep.nomr,bridging_sep.nama_pasien,bridging_sep.tglsep,"+
                                "bridging_sep.tglrujukan,bridging_sep.no_rujukan,bridging_sep.kdppkrujukan,"+
                                "bridging_sep.nmppkrujukan,bridging_sep.kdppkpelayanan,bridging_sep.nmppkpelayanan,"+
                                "if(bridging_sep.jnspelayanan='1','Rawat Inap','Rawat Jalan'),bridging_sep.catatan,bridging_sep.diagawal,"+
                                "bridging_sep.nmdiagnosaawal,bridging_sep.kdpolitujuan,bridging_sep.nmpolitujuan,"+
                                "if(bridging_sep.klsrawat='1','Kelas 1',if(bridging_sep.klsrawat='2','Kelas 2','Kelas 3')),"+
                                "if(bridging_sep.lakalantas='0','Kasus Kecelakaan','Bukan Kasus Kecelakaan'),concat(bridging_sep.nmkec,', ',bridging_sep.nmkab,', ',bridging_sep.nmprop) as lokasilaka,bridging_sep.user, "+
                                "bridging_sep.tanggal_lahir,bridging_sep.peserta,bridging_sep.jkel,bridging_sep.no_kartu,bridging_sep.asal_rujukan,bridging_sep.eksekutif,bridging_sep.cob,bridging_sep.penjamin,bridging_sep.notelep from bridging_sep where no_sep='"+NoSEP+"'",param);
                    }else{
                        Valid.MyReportqry("rptBridgingSEP2.jasper","report","::[ Cetak SEP ]::","select bridging_sep.no_sep, bridging_sep.no_rawat,bridging_sep.nomr,bridging_sep.nama_pasien,bridging_sep.tglsep,"+
                                "bridging_sep.tglrujukan,bridging_sep.no_rujukan,bridging_sep.kdppkrujukan,"+
                                "bridging_sep.nmppkrujukan,bridging_sep.kdppkpelayanan,bridging_sep.nmppkpelayanan,"+
                                "if(bridging_sep.jnspelayanan='1','Rawat Inap','Rawat Jalan'),bridging_sep.catatan,bridging_sep.diagawal,"+
                                "bridging_sep.nmdiagnosaawal,bridging_sep.kdpolitujuan,bridging_sep.nmpolitujuan,"+
                                "if(bridging_sep.klsrawat='1','Kelas 1',if(bridging_sep.klsrawat='2','Kelas 2','Kelas 3')),"+
                                "if(bridging_sep.lakalantas='0','Kasus Kecelakaan','Bukan Kasus Kecelakaan'),concat(bridging_sep.nmkec,', ',bridging_sep.nmkab,', ',bridging_sep.nmprop) as lokasilaka,bridging_sep.user, "+
                                "bridging_sep.tanggal_lahir,bridging_sep.peserta,bridging_sep.jkel,bridging_sep.no_kartu,bridging_sep.asal_rujukan,bridging_sep.eksekutif,bridging_sep.cob,bridging_sep.penjamin,bridging_sep.notelep from bridging_sep where no_sep='"+NoSEP+"'",param);
                    }                
                    this.setCursor(Cursor.getDefaultCursor());
                }else if(tbData.getValueAt(i,1).toString().equals("regis+label+sep")){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();                 
                    param.put("nama",NamaPasien);
                    param.put("alamat",Sequel.cariIsi("select date_format(tgl_lahir,'%d/%m/%Y') from pasien where no_rkm_medis=?",NoRm));
                    param.put("norm",NoRm);    
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    param.put("logo",Sequel.cariGambar("select bpjs from gambar")); 
                    param.put("prb",Sequel.cariIsi("select prb from bpjs_prb where no_sep=?",NoSEP));
                    Valid.MyReportqry("rptBuktiRegister.jasper","report","::[ Bukti Register ]::",
                           "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,pasien.no_tlp,"+
                           "reg_periksa.kd_dokter,dokter.nm_dokter,reg_periksa.no_rkm_medis,pasien.nm_pasien,pasien.jk,pasien.umur as umur,poliklinik.nm_poli,"+
                           "reg_periksa.p_jawab,reg_periksa.almt_pj,reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.stts_daftar,penjab.png_jawab "+
                           "from reg_periksa inner join dokter inner join pasien inner join poliklinik inner join penjab "+
                           "on reg_periksa.kd_dokter=dokter.kd_dokter and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                           "and reg_periksa.kd_pj=penjab.kd_pj and reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.no_rawat='"+NoRawat+"' ",param);
                    this.setCursor(Cursor.getDefaultCursor());
                    Valid.MyReportqry("rptBarcodeRawat.jasper","report","::[ Barcode No.Rawat ]::",
                            "SELECT reg_periksa.no_rawat,pasien.nm_pasien,reg_periksa.no_rkm_medis,pasien.tgl_lahir,pasien.no_ktp FROM reg_periksa INNER JOIN pasien ON reg_periksa.no_rkm_medis=pasien.no_rkm_medis WHERE reg_periksa.no_rawat='"+NoRawat+"'",param); 
                    this.setCursor(Cursor.getDefaultCursor());
                    if(JenisPelayanan.equals("ranap")){
                        Valid.MyReportqry("rptBridgingSEP.jasper","report","::[ Cetak SEP ]::","select bridging_sep.no_sep, bridging_sep.no_rawat,bridging_sep.nomr,bridging_sep.nama_pasien,bridging_sep.tglsep,"+
                                "bridging_sep.tglrujukan,bridging_sep.no_rujukan,bridging_sep.kdppkrujukan,"+
                                "bridging_sep.nmppkrujukan,bridging_sep.kdppkpelayanan,bridging_sep.nmppkpelayanan,"+
                                "if(bridging_sep.jnspelayanan='1','Rawat Inap','Rawat Jalan'),bridging_sep.catatan,bridging_sep.diagawal,"+
                                "bridging_sep.nmdiagnosaawal,bridging_sep.kdpolitujuan,bridging_sep.nmpolitujuan,"+
                                "if(bridging_sep.klsrawat='1','Kelas 1',if(bridging_sep.klsrawat='2','Kelas 2','Kelas 3')),"+
                                "if(bridging_sep.lakalantas='0','Kasus Kecelakaan','Bukan Kasus Kecelakaan'),concat(bridging_sep.nmkec,', ',bridging_sep.nmkab,', ',bridging_sep.nmprop) as lokasilaka,bridging_sep.user, "+
                                "bridging_sep.tanggal_lahir,bridging_sep.peserta,bridging_sep.jkel,bridging_sep.no_kartu,bridging_sep.asal_rujukan,bridging_sep.eksekutif,bridging_sep.cob,bridging_sep.penjamin,bridging_sep.notelep from bridging_sep where no_sep='"+NoSEP+"'",param);
                    }else{
                        Valid.MyReportqry("rptBridgingSEP2.jasper","report","::[ Cetak SEP ]::","select bridging_sep.no_sep, bridging_sep.no_rawat,bridging_sep.nomr,bridging_sep.nama_pasien,bridging_sep.tglsep,"+
                                "bridging_sep.tglrujukan,bridging_sep.no_rujukan,bridging_sep.kdppkrujukan,"+
                                "bridging_sep.nmppkrujukan,bridging_sep.kdppkpelayanan,bridging_sep.nmppkpelayanan,"+
                                "if(bridging_sep.jnspelayanan='1','Rawat Inap','Rawat Jalan'),bridging_sep.catatan,bridging_sep.diagawal,"+
                                "bridging_sep.nmdiagnosaawal,bridging_sep.kdpolitujuan,bridging_sep.nmpolitujuan,"+
                                "if(bridging_sep.klsrawat='1','Kelas 1',if(bridging_sep.klsrawat='2','Kelas 2','Kelas 3')),"+
                                "if(bridging_sep.lakalantas='0','Kasus Kecelakaan','Bukan Kasus Kecelakaan'),concat(bridging_sep.nmkec,', ',bridging_sep.nmkab,', ',bridging_sep.nmprop) as lokasilaka,bridging_sep.user, "+
                                "bridging_sep.tanggal_lahir,bridging_sep.peserta,bridging_sep.jkel,bridging_sep.no_kartu,bridging_sep.asal_rujukan,bridging_sep.eksekutif,bridging_sep.cob,bridging_sep.penjamin,bridging_sep.notelep from bridging_sep where no_sep='"+NoSEP+"'",param);
                    }                
                    this.setCursor(Cursor.getDefaultCursor());
                
                }
            }
        }
        
        
        
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void UploadSEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadSEPActionPerformed
        for(i=0;i<tbData.getRowCount();i++){ 
            if(tbData.getValueAt(i,0).toString().equals("true")){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgBerkasRawat berkas=new DlgBerkasRawat(null,true);
            berkas.setJudul("::[ Berkas Digital Perawatan ]::","berkasrawat/pages");
            try {
                berkas.loadURL("http://"+koneksiDB.HOSTHYBRIDWEB()+":"+koneksiDB.PORTWEB()+"/"+koneksiDB.HYBRIDWEB()+"/"+"berkasrawat/login2.php?act=login&usere=admin&passwordte=akusayangsamakamu&no_rawat="+NoRawat);             
            } catch (Exception ex) {
                System.out.println("Notifikasi : "+ex);
            }

            berkas.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
            berkas.setLocationRelativeTo(internalFrame1);        
            berkas.setVisible(true);        
            this.setCursor(Cursor.getDefaultCursor());
        }
        }    
    }//GEN-LAST:event_UploadSEPActionPerformed

    private void TNoRwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoRwActionPerformed
        
    }//GEN-LAST:event_TNoRwActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgPilihanCetakDokumen dialog = new DlgPilihanCetakDokumen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.ScrollPane Scroll;
    private widget.TextBox TNoRw;
    private javax.swing.JButton UploadSEP;
    private widget.InternalFrame internalFrame1;
    private widget.panelisi panelisi3;
    private widget.Table tbData;
    // End of variables declaration//GEN-END:variables

//    public void emptTeks() {
//        String NoSEP
//    }
    
    public void tampil() {
        try{         
            Valid.tabelKosong(TabMode);
            TabMode.addRow(new Object[]{false,"Bukti Registrasi"});//0,0
            TabMode.addRow(new Object[]{false,"Label Pasien"});//1,0
            TabMode.addRow(new Object[]{false,"Cetak Kartu Pasien"});//2,0
            TabMode.addRow(new Object[]{false,"Lembar SEP Model 1"});//3,0
            TabMode.addRow(new Object[]{false,"regis+label+sep"});//4,0
            
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
    }
    
    public void tampil2() {
        try{         
            Valid.tabelKosong(TabMode);
            TabMode.addRow(new Object[]{false,"Kartu Pasien 1"});//0,0
            TabMode.addRow(new Object[]{false,"Kartu Pasien 2"});//1,0
            TabMode.addRow(new Object[]{false,"Kartu Pasien 3"});//2,0
            TabMode.addRow(new Object[]{false,"Kartu Pasien 4"});//3,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 1"});//4,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 2"});//5,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 3"});//6,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 4"});//7,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 5"});//8,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 6"});//9,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 7"});//10,0
            TabMode.addRow(new Object[]{false,"Identitas Pasien 1"});//11,0
            TabMode.addRow(new Object[]{false,"Identitas Pasien 2"});//12,0
            TabMode.addRow(new Object[]{false,"Kartu Indeks Pasien"});//13,0
            TabMode.addRow(new Object[]{false,"Lembar Rawat Jalan Model 1"});//14,0
            TabMode.addRow(new Object[]{false,"Lembar Rawat Jalan Model 2"});//15,0
            TabMode.addRow(new Object[]{false,"Lembar Rawat Jalan Model 3"});//16,0
            TabMode.addRow(new Object[]{false,"Formulir Pendaftaran Pasien"});//17,0
            TabMode.addRow(new Object[]{false,"Lembar Screening Awal Pasien Masuk Rawat Jalan"});//18,0
            TabMode.addRow(new Object[]{false,"Formulir Penempelan Copy Resep"});//19,0
            TabMode.addRow(new Object[]{false,"Bukti Register 1"});//20,0
            TabMode.addRow(new Object[]{false,"Bukti Register 2"});//21,0
            TabMode.addRow(new Object[]{false,"Persetujuan Medis"});//22,0
            TabMode.addRow(new Object[]{false,"Surat Jaminan & Bukti Pelayanan Ralan"});//23,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kanan"});//24,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kiri"});//25,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kanan+Tracker"});//26,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kiri+Tracker"});//26,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kanan"});//27,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kiri"});//28,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kanan 2"});//29,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kiri 2"});//30,0
            TabMode.addRow(new Object[]{false,"Label Tracker 1"});//31,0
            TabMode.addRow(new Object[]{false,"Label Tracker 2"});//32,0
            TabMode.addRow(new Object[]{false,"Label Tracker 3"});//33,0
            TabMode.addRow(new Object[]{false,"Label Tracker 4"});//34,0
            TabMode.addRow(new Object[]{false,"Barcode Perawatan"});//35,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 1"});//36,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 2"});//37,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 3"});//38,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 4"});//39,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 5"});//40,0
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
    }
    
    public void tampil3() {
        try{         
            Valid.tabelKosong(TabMode);
            TabMode.addRow(new Object[]{false,"Kartu Pasien 1"});//0,0
            TabMode.addRow(new Object[]{false,"Kartu Pasien 2"});//1,0
            TabMode.addRow(new Object[]{false,"Kartu Pasien 3"});//2,0
            TabMode.addRow(new Object[]{false,"Kartu Pasien 4"});//3,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 1"});//4,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 2"});//5,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 3"});//6,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 4"});//7,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 5"});//8,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 6"});//9,0
            TabMode.addRow(new Object[]{false,"Label Rekam Medis 7"});//10,0
            TabMode.addRow(new Object[]{false,"Identitas Pasien 1"});//11,0
            TabMode.addRow(new Object[]{false,"Identitas Pasien 2"});//12,0
            TabMode.addRow(new Object[]{false,"Kartu Indeks Pasien"});//13,0
            TabMode.addRow(new Object[]{false,"Lembar Rawat Jalan Model 1"});//14,0
            TabMode.addRow(new Object[]{false,"Lembar Rawat Jalan Model 2"});//15,0
            TabMode.addRow(new Object[]{false,"Lembar Rawat Jalan Model 3"});//16,0
            TabMode.addRow(new Object[]{false,"Formulir Pendaftaran Pasien"});//17,0
            TabMode.addRow(new Object[]{false,"Lembar Screening Awal Pasien Masuk Rawat Jalan"});//18,0
            TabMode.addRow(new Object[]{false,"Formulir Penempelan Copy Resep"});//19,0
            TabMode.addRow(new Object[]{false,"Bukti Register 1"});//20,0
            TabMode.addRow(new Object[]{false,"Bukti Register 2"});//20,0
            TabMode.addRow(new Object[]{false,"Persetujuan Medis"});//21,0
            TabMode.addRow(new Object[]{false,"Surat Jaminan & Bukti Pelayanan Ralan"});//22,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kanan"});//23,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kiri"});//24,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kanan+Tracker"});//25,0
            TabMode.addRow(new Object[]{false,"Check List Kelengkapan Pendaftaran Kiri+Tracker"});//26,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kanan"});//27,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kiri"});//28,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kanan 2"});//29,0
            TabMode.addRow(new Object[]{false,"Lembar Periksa Pasien Kiri 2"});//30,0
            TabMode.addRow(new Object[]{false,"Label Tracker 1"});//31,0
            TabMode.addRow(new Object[]{false,"Label Tracker 2"});//32,0
            TabMode.addRow(new Object[]{false,"Label Tracker 3"});//33,0
            TabMode.addRow(new Object[]{false,"Label Tracker 4"});//34,0
            TabMode.addRow(new Object[]{false,"Barcode Perawatan"});//35,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 1"});//36,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 2"});//37,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 3"});//38,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 4"});//39,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ralan 5"});//40,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ranap 1"});//41,0
            TabMode.addRow(new Object[]{false,"Gelang Pasien Ranap 2"});//42,0
            TabMode.addRow(new Object[]{false,"Lembar SJP"});//43,0
            TabMode.addRow(new Object[]{false,"PDF SJP"});//43,0
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
    }
    
    
    public void setNoRm(String NoRawat,String NoRm,String NoSEP,String NoReg,String NamaPoli,
        String NamaBayar,String NamaDokter,String NamaPasien,String AlamatPasien,
        String PenanggungJawab,String TanggalDaftar, String JenisPelayanan) {
            TNoRw.setText(NoSEP+" "+ NamaPasien+" "+NoRm+" "+NamaPoli+" "+NamaDokter);
            this.NoRawat=NoRawat;
            this.NoRm=NoRm;
            this.NoSEP=NoSEP;
            this.NoReg=NoReg;
            this.NamaPoli=NamaPoli;
            this.NamaBayar=NamaBayar;
            this.NamaPasien=NamaPasien;
            this.AlamatPasien=AlamatPasien;
            this.NamaDokter=NamaDokter;
            this.PenanggungJawab=PenanggungJawab;
            this.TanggalDaftar=TanggalDaftar;
            this.JenisPelayanan=JenisPelayanan;
    }

    public void setNoRm(String text, String text0, String nosep, String text1, String text2, String text3, String text4, String string, String text5, String SetTgl, String ranap) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
